myproject/jotlists/urls.py
from django.urls import path

from . import views

app_name = 'jotlists'
urlpatterns = [
    path('', views.index, name='index'),
    path('/<int:list_id>/remove_list', views.remove_list, name='remove_list'),
    path('/<int:topic_id>/remove_topic', views.remove_topic, name='remove_topic'),
    path('/create_list', views.create_list, name='create_list'),
    path('/create_topic', views.create_topic, name='create_topic'),
]

myproject/myproject/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.index, name='index'),
    path('ToDo', include('todolists.urls')),
    path('RemindMe', include('reminders.urls')),
    path('JotItDown', include('jotlists.urls')),
    path('admin', admin.site.urls),
]

myproject/reminders/urls.py
from django.urls import path

from . import views

app_name = 'reminders'
urlpatterns = [
    path('', views.index, name='index'),
    path('/add', views.add, name='add'),
    path('/create', views.create, name='create'),
    path('/<int:reminder_id>/remove', views.remove, name='remove'),
    path('/<int:reminder_id>/', views.detail, name='detail'),
]

myproject/reminders/models.py
from django.db import models


class Reminder(models.Model):
    issued_date = models.DateTimeField('date created')
    text = models.CharField(max_length=100)
    topic_name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    start_date = models.DateTimeField('start date')
    end_date = models.DateTimeField('end date')

    def __str__(self):
        return self.text

myproject/reminders/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Reminder
from django.utils import timezone


def index(request):
    reminder_past = Reminder.objects.filter(end_date__lte=timezone.now()).order_by('-issued_date')
    reminder_upcoming = Reminder.objects.filter(start_date__gte=timezone.now()).order_by('-issued_date')
    reminder_live = Reminder.objects.filter(start_date__lte=timezone.now()).filter(
                    end_date__gte=timezone.now()).order_by('-issued_date')
    context = {'reminder_past': reminder_past, 'reminder_upcoming': reminder_upcoming, 'reminder_live': reminder_live}
    return render(request, 'reminders/index.html', context)


def detail(request, reminder_id):
    reminder = get_object_or_404(Reminder, pk=reminder_id)
    return render(request, 'reminders/detail.html', {'reminder': reminder})


def create(request):
    try:
        reminder = Reminder(text=request.POST['reminder_text'], topic_name=request.POST['topic_title'],
                            description=request.POST['description'],
                            start_date=request.POST['start_date'], end_date=request.POST['end_date'])
        reminder.issued_date = timezone.now()
        if reminder.start_date >= reminder.end_date:
            raise KeyError
    except KeyError:
        reminder_past = Reminder.objects.filter(end_date__lte=timezone.now()).order_by('-issued_date')
        reminder_upcoming = Reminder.objects.filter(start_date__gte=timezone.now()).order_by('-issued_date')
        reminder_live = Reminder.objects.filter(start_date__lte=timezone.now()).filter(
            end_date__gte=timezone.now()).order_by('-issued_date')
        context = {'reminder_past': reminder_past, 'reminder_upcoming': reminder_upcoming,
                   'reminder_live': reminder_live, 'error_message': "Invalid input!"}
        return render(request, 'reminders/index.html', context)
    else:
        reminder.save()
        return HttpResponseRedirect(reverse('reminders:index', args=()))


def add(request):
    return render(request, 'reminders/add.html', {})


def remove(request, reminder_id):
    try:
        reminder = Reminder.objects.get(pk=reminder_id)
    except (KeyError, Reminder.DoesNotExist):
        reminder_past = Reminder.objects.filter(end_date__lte=timezone.now()).order_by('-issued_date')
        reminder_upcoming = Reminder.objects.filter(start_date__gte=timezone.now()).order_by('-issued_date')
        reminder_live = Reminder.objects.filter(start_date__lte=timezone.now()).filter(
            end_date__gte=timezone.now()).order_by('-issued_date')
        context = {'reminder_past': reminder_past, 'reminder_upcoming': reminder_upcoming,
                   'reminder_live': reminder_live, 'error_message': "Such a topic does not exist!"}
        return render(request, 'reminders/index.html', context)
    else:
        reminder.delete()
        return HttpResponseRedirect(reverse('reminders:index', args=()))

myproject/templates/reminders/add.html
{% extends "reminders\base.html" %}

{% block content %}
<br>
{% if error_message %}<p><strong>{{ error_message }}</strong></p><br>{% endif %}
<h5 style="float:center;">Create a new reminder...</h5><br><br>
<form action="{% url 'reminders:create' %}" method="post">
    {% csrf_token %}
  <div class="form-group" style="width:80%;">
    <label for="reminder_text" style="float:left;">Name : </label>
    <input type="text" class="form-control" id="reminder_text" name="reminder_text" placeholder="Enter name of reminder" required>
  </div>
  <div class="form-group" style="width:80%;">
    <label for="topic_title"  style="float:left;">Topic : </label>
    <input type="text" class="form-control" id="topic_title" name="topic_title" placeholder="Enter topic">
  </div>
  <div class="form-group" style="width:80%;">
    <label for="description" style="float:left;">Description : </label>
    <textarea rows="3" class="form-control" id="description" name="description" placeholder="Enter description"></textarea>
  </div>
<br>
  <div class="form-group" style="width:80%;">
    <label for="start_date" style="float:left;">Start date : </label>
      <div class='input-group date' id='start_date'>
          <input type='text' class="form-control" name="start_date" required/>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>
  </div>
  <div class="form-group" style="width:80%;">
      <label for="end_date" style="float:left;">End date : </label>
      <div class='input-group date' id='end_date'>
          <input type='text' class="form-control" name="end_date" required/>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>
  </div>

<br><br>

  <input class="btn btn-primary" style="float:right" type="submit" value="Create">
</form>
<script type="text/javascript">
    $('#start_date').datetimepicker({
        format:'YYYY-MM-DD HH:MM',
        minDate: getFormattedDate(new Date())
    });
    $('#end_date').datetimepicker({
        format:'YYYY-MM-DD HH:MM',
        minDate: getFormattedDate(new Date())
    });
    function getFormattedDate(date) {
         var day = date.getDate();
         var month = date.getMonth() + 1;
         var year = date.getFullYear().toString();
         return year + '-' + month + '-' + day + ' 00:00';
     }
</script>
{% endblock content %}

myproject/templates/reminders/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <title>Remind Me</title>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="/" style="font-family:Times New Roman; font-size:200%;">Pin It Up App</a>
  <p style="color:white; margin: 10px;">Your one-stop solution to record all your work</p>
</nav>
<div class="jumbotron jumbotron-fluid text-dark">
  <div class="container-fluid">
    <center>
      <div class="card" style="width:95%;" align="center" >
        <h3 class="card-title" style="font-size: xx-large;" align="center"><br><b>Remind Me</b></h3>
        <p class="card-subtitle" style="font-size: medium; margin-right: 30px;" align="center"><br>List all your reminders here..... We will remind you</p>
        <div class="card-body" style="font-size: regular;">
        {% block content %}
        {% endblock content %}
        </div>
      </div>
    </center>
  </div>
</div>

</body>
</html>

myproject/templates/reminders/detail.html
{% extends "reminders\base.html" %}

{% block content %}
<br>
{% if error_message %}<p><strong>{{ error_message }}</strong></p><br>{% endif %}

{% if reminder %}
   <div class="card text-center p-5" style="width: 65rem; margin:20px;">
      <div class="card-body">
         <div>
            <h3 class="card-title" style="font-size:24px; color:red;">{{ reminder.text }}</h3>
            <p style="float:right; font-size:14px;"> - {{ reminder.issued_date }}</p><br>
         </div>
        <div>
            {% if reminder.topic_name %}
        <p class="card-text" style="font-size:21px; align:center; color:blue;"><i>Topic: {{ reminder.topic_name }}</i></p>
            {% endif %}
        </div>
        <div>
            <p class="card-text" style="font-size:17px;"><br>
                Start date : {{ reminder.start_date }}<br>
                End date : {{ reminder.end_date }}<br>
            {% if reminder.description %}
              <br>{{ reminder.description }}<br>
            {% endif %}
              </p>
        </div>
      </div>
   </div>
<br>
<br>
{% endif %}
{% endblock content %}

myproject/templates/reminders/index.html
{% extends "reminders\base.html" %}

{% block content %}
<br>
{% if error_message %}<p><strong>{{ error_message }}</strong></p><br>{% endif %}

<a class="btn btn-primary" href="{% url 'reminders:add' %}">Add new reminder</a>
<br>
<br>
<div class="container">
        <a class="btn btn-info" href="#Live" role="button"><span class="spinner-grow spinner-grow-sm"></span> Live</a>
        <a class="btn btn-info" href="#Upcoming" role="button">Upcoming</a>
        <a class="btn btn-info" href="#Past" role="button">Past</a>
</div>
<br>
<br>
<div class="card text-center p-1" style="width: 80rem;">
  <div class="card-body">
       <a class="card-title" name="Live" style="font-size: 22px; float:center; "><b>Live</b></a>
      <br>
      <br>
       {% if reminder_live %}
          <ul class="list-group p-3">
          {% for reminder in reminder_live %}
              <li class="list-group-item p-5" style="text-align:left; font-size:17px;">
                 <div>
                    <span style="font-size:22px;"><u><i>{{ reminder.text }}</i></u></span><br>
                    <span class="float-right" style="font-size: 14px;">{{ reminder.start_date }} - {{ reminder.end_date }}</span>
                 </div>
                  <br>
                 <div>
                  {% if reminder.topic_name %}
                     {{ reminder.topic_name }}
                  {% endif %}
                 </div>
                <br>
                <div class="float-right" style="font-size: small">
                    <a href="{% url 'reminders:detail' reminder.id %}" class="btn btn-success">View</a>
                    <a href="{% url 'reminders:remove' reminder.id %}" class="btn btn-danger">Delete</a>
                </div>
             </li>
              <br>
              <br>
          {% endfor %}
          </ul>
        {% else %}
           <p>No reminder available</p>
        {% endif %}
  </div>
</div>
<br><br>
<div class="card text-center p-1" style="width: 80rem;">
  <div class="card-body">
       <a class="card-title" name="Upcoming" style="font-size: 22px; float:center; "><b>Upcoming</b></a>
      <br>
      <br>
      {% if reminder_upcoming %}
          <ul class="list-group p-3">
          {% for reminder in reminder_upcoming %}
              <li class="list-group-item p-5" style="text-align:left; font-size:17px;">
                 <div>
                    <span style="font-size:22px;"><u><i>{{ reminder.text }}</i></u></span><br>
                    <span class="float-right" style="font-size: 14px;">{{ reminder.start_date }} - {{ reminder.end_date }}</span>
                 </div>
                  <br>
                 <div>
                  {% if reminder.topic_name %}
                     {{ reminder.topic_name }}
                  {% endif %}
                 </div>
                <br>
                <div class="float-right" style="font-size: small">
                    <a href="{% url 'reminders:detail' reminder.id %}" class="btn btn-success">View</a>
                    <a href="{% url 'reminders:remove' reminder.id %}" class="btn btn-danger">Delete</a>
                </div>
             </li>
          {% endfor %}
          </ul>
        {% else %}
           <p>No reminder available</p>
        {% endif %}
  </div>
</div>
<br><br>
<div class="card text-center p-1" style="width: 80rem;">
  <div class="card-body">
       <a class="card-title" name="Past" style="font-size: 22px; float:center; "><b>Past</b></a>
      <br>
      <br>
      {% if reminder_past %}
          <ul class="list-group p-3">
          {% for reminder in reminder_past %}
              <li class="list-group-item p-5" style="text-align:left; font-size:17px;">
                 <div>
                    <span style="font-size:22px;"><u><i>{{ reminder.text }}</i></u></span><br>
                    <span class="float-right" style="font-size: 14px;">{{ reminder.start_date }} - {{ reminder.end_date }}</span>
                 </div>
                  <br>
                 <div>
                  {% if reminder.topic_name %}
                     {{ reminder.topic_name }}
                  {% endif %}
                 </div>
                <br>
                <div class="float-right" style="font-size: small">
                    <a href="{% url 'reminders:detail' reminder.id %}" class="btn btn-success">View</a>
                    <a href="{% url 'reminders:remove' reminder.id %}" class="btn btn-danger">Delete</a>
                </div>
             </li>
          {% endfor %}
          </ul>
        {% else %}
           <p>No reminder available</p>
        {% endif %}
  </div>
</div>
<br>
<br>
{% endblock content %}