myproject/jotlists/urls.py
from django.urls import path

from . import views

app_name = 'jotlists'
urlpatterns = [
    path('', views.index, name='index'),
    path('/<int:list_id>/remove_list', views.remove_list, name='remove_list'),
    path('/<int:topic_id>/remove_topic', views.remove_topic, name='remove_topic'),
    path('/create_list', views.create_list, name='create_list'),
    path('/create_topic', views.create_topic, name='create_topic'),
]

myproject/myproject/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.index, name='index'),
    path('ToDo', include('todolists.urls')),
    path('RemindMe', include('reminders.urls')),
    path('JotItDown', include('jotlists.urls')),
    path('admin', admin.site.urls),
]

myproject/todolists/urls.py
from django.urls import path

from . import views

app_name = 'todolists'

urlpatterns = [
    path('', views.index, name='index'),
    path('/<int:task_id>/remove', views.remove, name='remove'),
    path('/create', views.create, name='create'),
]

myproject/todolists/models.py
from django.db import models


class Todo(models.Model):
    added_date = models.DateTimeField('date created')
    text = models.CharField(max_length=300)

    def __str__(self):
        return self.text

myproject/todolists/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Todo
from django.utils import timezone


def index(request):
    todo_list = Todo.objects.order_by('-added_date')
    context = {'todo_list': todo_list}
    return render(request, 'todolists/index.html', context)


def remove(request, task_id):
    try:
        task = Todo.objects.get(pk=task_id)
    except (KeyError, Todo.DoesNotExist):
        return render(request, 'todolists/index.html', {
            'todo_list': Todo.objects.order_by('-added_date'),
            'error_message': "Such a task does not exist!",
        })
    else:
        task.delete()
        return HttpResponseRedirect(reverse('todolists:index', args=()))


def create(request):
    try:
        task = Todo(text=request.POST['task_text'], added_date=timezone.now())
        if task.text is "":
            raise KeyError
    except KeyError:
        return render(request, 'todolists/index.html', {
            'todo_list': Todo.objects.order_by('-added_date'),
            'error_message': "Can't create an empty task.",
        })
    else:
        task.save()
        return HttpResponseRedirect(reverse('todolists:index', args=()))


myproject/templates/todolists/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <title>Todo-list</title>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="/" style="font-family:Times New Roman; font-size:200%;">Pin It Up App</a>
  <p style="color:white; margin: 10px;">Your one-stop solution to record all your work</p>
</nav>
<div class="jumbotron jumbotron-fluid text-dark">
  <div class="container-fluid">
    <center>
      <div class="card" style="width:95%;" align="center" >
        <h3 class="card-title" style="font-size: 30px;" align="center"><br><b>To-Do list</b></h3>
        <p class="card-subtitle" style="font-size: 18px;" align="center"><br>List all your to-do works here.....</p>
        <div class="card-body" style="font-size: regular;">
        {% block content %}
        {% endblock content %}
        </div>
      </div>
    </center>
  </div>
</div>

</body>
</html>

myproject/templates/todolists/index.html
{% extends "todolists\base.html" %}

{% block content %}
<br>
{% if error_message %}<p><strong>{{ error_message }}</strong></p><br>{% endif %}

<form action="{% url 'todolists:create' %}" method="post">
    {% csrf_token %}
    <div class="form-group col-lg-8">
    <textarea class="form-control" rows="3" cols="50" name="task_text" id="task_text" placeholder="Type something here ..."></textarea>
    <br>
    <input class="btn btn-primary" style="float:right" type="submit" value="Add">
    </div>
</form>
<br>
<br>
<br>

{% if todo_list %}
    <ul class="list-group">
    {% for task in todo_list %}
        <li class="list-group-item" style="text-align:left">{{ task.text }}
            <div class="float-right" style="font-size: small"><i>- {{ task.added_date }}  </i>
             <a href="{% url 'todolists:remove' task.id %}" class="btn btn-danger">Delete</a></div>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tasks are available.</p>
{% endif %}
{% endblock content %}