myproject/jotlists/urls.py
from django.urls import path

from . import views

app_name = 'jotlists'
urlpatterns = [
    path('', views.index, name='index'),
    path('/<int:list_id>/remove_list', views.remove_list, name='remove_list'),
    path('/<int:topic_id>/remove_topic', views.remove_topic, name='remove_topic'),
    path('/create_list', views.create_list, name='create_list'),
    path('/create_topic', views.create_topic, name='create_topic'),
]

myproject/myproject/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.index, name='index'),
    path('ToDo', include('todolists.urls')),
    path('RemindMe', include('reminders.urls')),
    path('JotItDown', include('jotlists.urls')),
    path('admin', admin.site.urls),
]

myproject/jotlists/models.py
from django.db import models


class Topic(models.Model):
    issued_date = models.DateTimeField('date created')
    topic_name = models.CharField(max_length=100)

    def __str__(self):
        return self.topic_name


class List(models.Model):
    list_text = models.CharField(max_length=200)
    topic_title = models.ForeignKey(Topic, on_delete=models.CASCADE)

    def __str__(self):
        return self.list_text


myproject/jotlists/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Topic, List
from django.utils import timezone


def index(request):
    topic_list = Topic.objects.order_by('issued_date')
    context = {'topic_list': topic_list}
    return render(request, 'jotlists/index.html', context)


def remove_list(request, list_id):
    try:
        list_name = List.objects.get(pk=list_id)
    except (KeyError, List.DoesNotExist):
        return render(request, 'jotlists/index.html', {
            'topic_list': Topic.objects.order_by('issued_date'),
            'error_message': "Such a list does not exist!",
        })
    else:
        list_name.delete()
        return HttpResponseRedirect(reverse('jotlists:index', args=()))


def remove_topic(request, topic_id):
    try:
        topic_name = Topic.objects.get(pk=topic_id)
    except (KeyError, Topic.DoesNotExist):
        return render(request, 'jotlists/index.html', {
            'topic_list': Topic.objects.order_by('issued_date'),
            'error_message': "Such a topic does not exist!",
        })
    else:
        topic_name.delete()
        return HttpResponseRedirect(reverse('jotlists:index', args=()))


def create_list(request):
    try:
        task = List(list_text=request.POST['list_text'], topic_title=Topic.objects.get(pk=request.POST['topic_title']))
        if task.list_text is "":
            raise KeyError
    except KeyError:
        return render(request, 'jotlists/index.html', {
            'topic_list': Topic.objects.order_by('issued_date'),
            'error_message': "Can't create an item with no name!",
        })
    else:
        task.save()
        return HttpResponseRedirect(reverse('jotlists:index', args=()))


def create_topic(request):
    try:
        topic = Topic(topic_name=request.POST['topic_name'], issued_date=timezone.now())
        if topic.topic_name is "":
            raise KeyError
    except KeyError:
        return render(request, 'jotlists/index.html', {
            'topic_list': Topic.objects.order_by('issued_date'),
            'error_message': "Can't create a topic with no name!",
        })
    else:
        topic.save()
        return HttpResponseRedirect(reverse('jotlists:index', args=()))

myproject/templates/jotlists/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <title>Jot It Down</title>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="/" style="font-family:Times New Roman; font-size:200%;">Pin It Up App</a>
  <p style="color:white; margin: 10px;">Your one-stop solution to record all your work</p>
</nav>
<div class="jumbotron jumbotron-fluid text-dark">
  <div class="container-fluid">
    <center>
      <div class="card" style="width:95%;" align="center" >
        <h3 class="card-title" style="font-size: 30px;" align="center"><br><b>Jot It Down</b></h3>
        <p class="card-subtitle" style="font-size: 18px;" align="center"><br>List anything that you want in an organised manner</p>
        <div class="card-body" style="font-size: regular;">
        {% block content %}
        {% endblock content %}
        </div>
      </div>
    </center>
  </div>
</div>

</body>
</html>

myproject/templates/jotlists/index.html
{% extends "jotlists\base.html" %}

{% block content %}
<br>
{% if error_message %}<p><strong>{{ error_message }}</strong></p><br>{% endif %}

<form action="{% url 'jotlists:create_topic' %}" method="post">
    {% csrf_token %}
    <div class="form-group col-lg-8">
    <textarea class="form-control" cols="30" name="topic_name" id="topic_name" placeholder="Add a new topic....."></textarea>
    <br>
    <input class="btn btn-primary" style="float:right" type="submit" value="Create new topic">
    </div>
</form>
<br>
<br>
<br>


{% if topic_list %}
    {% for topic in topic_list %}
        <div class="card" style="width: 40rem;">
          <div class="card-body">
            <h3 class="card-title">{{ topic.topic_name }}</h3>
              <div class="float-right" style="font-size: small">
                 <a href="{% url 'jotlists:remove_topic' topic.id %}" class="btn btn-outline-danger">Delete topic</a>
              </div>
              <br><br><br>
              <form action="{% url 'jotlists:create_list' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group col-lg-8">
                    <textarea class="form-control" cols="30" name="list_text" id="list_text" placeholder="Add a new item ..."></textarea>
                    <input type="hidden" class="form-control" name="topic_title" id="topic_title" value="{{ topic.id }}">
                    <br>
                    <input class="btn btn-success" style="float:right" type="submit" value="Add new item">
                    </div>
                </form>
                <br>
                <br>
                {% if topic.list_set.all %}
                    <ul class="list-group">
                    {% for list in topic.list_set.all %}
                         <li class="list-group-item" style="text-align:left">{{ list.list_text }}
                        <div class="float-right" style="font-size: small">
                         <a href="{% url 'jotlists:remove_list' list.id %}" class="btn btn-danger">Delete item</a></div>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p>No item available</p>
                {% endif %}
            </div>
          </div><br>
    {% endfor %}
{% else %}
    <p>No topics are available.</p>
{% endif %}
{% endblock content %}