myproject/jotlists/urls.py
from django.urls import path

from . import views

app_name = 'jotlists'
urlpatterns = [
    path('', views.index, name='index'),
    path('/<int:list_id>/remove_list', views.remove_list, name='remove_list'),
    path('/<int:topic_id>/remove_topic', views.remove_topic, name='remove_topic'),
    path('/create_list', views.create_list, name='create_list'),
    path('/create_topic', views.create_topic, name='create_topic'),
]

myproject/myproject/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.index, name='index'),
    path('ToDo', include('todolists.urls')),
    path('RemindMe', include('reminders.urls')),
    path('JotItDown', include('jotlists.urls')),
    path('admin', admin.site.urls),
]

myproject/reminders/urls.py
from django.urls import path

from . import views

app_name = 'reminders'
urlpatterns = [
    path('', views.index, name='index'),
    path('/add', views.add, name='add'),
    path('/create', views.create, name='create'),
    path('/<int:reminder_id>/remove', views.remove, name='remove'),
    path('/<int:reminder_id>/', views.detail, name='detail'),
]

myproject/todolists/urls.py
from django.urls import path

from . import views

app_name = 'todolists'

urlpatterns = [
    path('', views.index, name='index'),
    path('/<int:task_id>/remove', views.remove, name='remove'),
    path('/create', views.create, name='create'),
]

myproject/templates/main/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
   <title>Pin It Up</title>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="/" style="font-family:Times New Roman; font-size:200%;">Pin It Up App</a>
  <p style="color:white; margin: 10px;">Your one-stop solution to record all your work</p>
</nav>

<div class="jumbotron jumbotron-fluid text-dark">
  <div class="container-fluid">
    <center>
      <div class="card" style="width:95%;" align="center" >
        <div class="card-title" style="font-size: xx-large;" align="center"><br><b>Pin It Up</b></div>
        <div class="card-body">
            <div class="row">
              <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">To-Do List</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="{% url 'todolists:index' %}" class="btn btn-primary">Go >></a>
                  </div>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Jot It Down</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="{% url 'jotlists:index' %}" class="btn btn-primary">Go >></a>
                  </div>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Remind Me</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="{% url 'reminders:index' %}" class="btn btn-primary">Go >></a>
                  </div>
                </div>
              </div>
            </div>
            <br><br>
        </div>
      </div>
    </center>
  </div>
</div>
</body>
</html>